language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

#matrix:
#    allow_failures:
#        - php: hhvm

install:
    # This line avoid weird error about permission when it try to clear:cache
#    - rm -rf app/cache
    - COMPOSER_ROOT_VERSION=dev-master composer --prefer-source install

script:
    - mkdir -p build/logs
#    - ./vendor/phpunit/phpunit/phpunit -c app/
    - make tests

after_script:
    - php bin/coveralls