imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
#        storage_id: session.storage.filesystem
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

# Liip Functional Tests
liip_functional_test: ~
#    cache_sqlite_db: true

doctrine:
    dbal:
        dbname: %database_name%_test
#        default_connection: default
#        connections:
#            default:
#                driver:  pdo_sqlite
#                dbname:  %database_name%_test
#                path:    %kernel.cache_dir%/test.db
#                charset: UTF8

#    orm:
#        auto_generate_proxy_classes: true
#        auto_mapping: true

lexik_jwt_authentication:
    private_key_path: %kernel.root_dir%/var/jwt/private_test.pem   # ssh private key path
    public_key_path:  %kernel.root_dir%/var/jwt/public_test.pem    # ssh public key path
    pass_phrase:      'bambou'                                # ssh key pass phrase

parameters:
    test.client.class: Dizda\Bundle\AppBundle\Tests\Client