dizda_app_withdraw:
    type:           rest
    resource:       @DizdaAppBundle/Controller/WithdrawController.php
    prefix:         /

dizda_app_withdraw_output:
    type:           rest
    resource:       @DizdaAppBundle/Controller/WithdrawOutputController.php
    prefix:         /

dizda_app_deposit:
    type:           rest
    resource:       @DizdaAppBundle/Controller/DepositController.php
    prefix:         /

dizda_app_address:
    type:           rest
    resource:       @DizdaAppBundle/Controller/AddressController.php
    prefix:         /